---

- name: "20.1 | Activate windows"
  win_shell: cscript slmgr.vbs /ipk XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
  args:
    chdir: C:\Windows\System32\
  when:
      - rule_20_1
  tags:
      - rule_20.1
      - patch

- name: "20.2 | Disable NetBIOS system wide"
  community.windows.win_netbios:
    state: disabled
  when:
      - rule_20_2
  tags:
      - rule_20.2
      - patch

- name: "20.3 | Set spooler service startup mode to manual and ensure it is stopped"
  ansible.windows.win_service:
    name: spooler
    start_mode: manual
    state: stopped
  when:
      - rule_20_3
  tags:
      - rule_20.3
      - patch

- name: "20.4 | Remove C pagefile"
  community.windows.win_pagefile:
    drive: C
    remove_all: yes
    automatic: no
    state: present
  when:
      - rule_20_4
  tags:
      - rule_20.4
      - patch

- name: "20.6 | Join Domain"
  win_domain_membership:
#      hostname: "{{ VM_NAME }}"
    dns_domain_name: bussan.co.id
    domain_admin_user: bussan.co.id\vcentersvc
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: OU=ansible,OU=Test_Vendor,DC=bussan,DC=co,DC=id
    state: domain
  register: domain_state
  notify: reboot_windows
  when:
      - rule_20_6
  tags:
      - rule_20.6
      - patch


- name: "20.7 | Install all updates and reboot as many times as needed"
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      # - CriticalUpdates
      # - UpdateRollups
    reboot: yes
  when:
      - rule_20_7
  tags:
      - rule_20.7
      - patch